export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const TOGGLE_SHOW_CART = 'TOGGLE_SHOW_CART';
export const TOGGLE_SHOW_SEARCH = 'TOGGLE_SHOW_SEARCH';
export const SET_SELECTED_PRODUCT = 'SET_SELECTED_PRODUCT';
